airflow:
  images:
    airflow:
      repository: apache/airflow
      tag: 2.2.4-python3.8
      pullPolicy: IfNotPresent

  dags:
    gitSync:
      enabled: true
      repo: git@github.com:kdrivas/infra-mlops.git
      subPath: scripts/airflow/dags
      sshKeySecret: airflow-ssh-secret

  extraSecrets:
    airflow-ssh-secret:
      data: |
        gitSshKey: ''