# Model
PARAM_GRID = {
    "selector__k": [3, 4, 5, 6, 7, 10], # The best parameters found in the experimentation step (notebooks)
    "model__alpha": [1, 0.5, 0.2, 0.1, 0.05, 0.02, 0.01],
    "poly__degree": [1, 2, 3, 5, 7]
}

# Features
TARGET_COL = "target"

PERIOD_COLS = [
    "anio",
    "mes",
]

PIB_COLS = [
    "PIB_Agropecuario_silvicola",
    "PIB_Pesca",
    "PIB_Mineria",
    "PIB_Mineria_del_cobre",
    "PIB_Otras_actividades_mineras",
    "PIB_Industria_Manufacturera",
    "PIB_Alimentos",
    "PIB_Bebidas_y_tabaco",
    "PIB_Textil",
    "PIB_Maderas_y_muebles",
    "PIB_Celulosa",
    "PIB_Refinacion_de_petroleo",
    "PIB_Quimica",
    "PIB_Minerales_no_metalicos_y_metalica_basica",
    "PIB_Productos_metalicos",
    "PIB_Electricidad",
    "PIB_Construccion",
    "PIB_Comercio",
    "PIB_Restaurantes_y_hoteles",
    "PIB_Transporte",
    "PIB_Comunicaciones",
    "PIB_Servicios_financieros",
    "PIB_Servicios_empresariales",
    "PIB_Servicios_de_vivienda",
    "PIB_Servicios_personales",
    "PIB_Administracion_publica",
    "PIB_a_costo_de_factores",
    "PIB",
]

IMACEC_INDICE_COLS = [
    "Imacec_empalmado",
    "Imacec_produccion_de_bienes",
    "Imacec_minero",
    "Imacec_industria",
    "Imacec_resto_de_bienes",
    "Imacec_comercio",
    "Imacec_servicios",
    "Imacec_a_costo_de_factores",
    "Imacec_no_minero",
    "Indice_de_ventas_comercio_real_no_durables_IVCM"
]

CITY_COLS = [
    "Coquimbo",
    "Valparaiso",
    "Metropolitana_de_Santiago",
    "Libertador_Gral__Bernardo_O_Higgins",
    "Maule",
    "Biobio",
    "La_Araucania",
    "Los_Rios"
]
    
MILK_COLS = PERIOD_COLS + ["Precio_leche"]

BANK_COLS = PERIOD_COLS + PIB_COLS + IMACEC_INDICE_COLS

PREP_COLS = PERIOD_COLS + CITY_COLS

MERGE_COLS = MILK_COLS + CITY_COLS + PIB_COLS + IMACEC_INDICE_COLS 

TAKE_VARS = [
    "Precio_leche_rolling3_mean",
    "Coquimbo_rolling3_mean",
    "Valparaiso_rolling3_mean",
    "Metropolitana_de_Santiago_rolling3_mean",
    "Libertador_Gral__Bernardo_O_Higgins_rolling3_mean",
    "Maule_rolling3_mean",
    "Biobio_rolling3_mean",
    "La_Araucania_rolling3_mean",
    "Los_Rios_rolling3_mean",
    "PIB_Agropecuario_silvicola_rolling3_mean",
    "PIB_Pesca_rolling3_mean",
    "PIB_Mineria_rolling3_mean",
    "PIB_Mineria_del_cobre_rolling3_mean",
    "PIB_Otras_actividades_mineras_rolling3_mean",
    "PIB_Industria_Manufacturera_rolling3_mean",
    "PIB_Alimentos_rolling3_mean",
    "PIB_Bebidas_y_tabaco_rolling3_mean",
    "PIB_Textil_rolling3_mean",
    "PIB_Maderas_y_muebles_rolling3_mean",
    "PIB_Celulosa_rolling3_mean",
    "PIB_Refinacion_de_petroleo_rolling3_mean",
    "PIB_Quimica_rolling3_mean",
    "PIB_Minerales_no_metalicos_y_metalica_basica_rolling3_mean",
    "PIB_Productos_metalicos_rolling3_mean",
    "PIB_Electricidad_rolling3_mean",
    "PIB_Construccion_rolling3_mean",
    "PIB_Comercio_rolling3_mean",
    "PIB_Restaurantes_y_hoteles_rolling3_mean",
    "PIB_Transporte_rolling3_mean",
    "PIB_Comunicaciones_rolling3_mean",
    "PIB_Servicios_financieros_rolling3_mean",
    "PIB_Servicios_empresariales_rolling3_mean",
    "PIB_Servicios_de_vivienda_rolling3_mean",
    "PIB_Servicios_personales_rolling3_mean",
    "PIB_Administracion_publica_rolling3_mean",
    "PIB_a_costo_de_factores_rolling3_mean",
    "PIB_rolling3_mean",
    "Imacec_empalmado_rolling3_mean",
    "Imacec_produccion_de_bienes_rolling3_mean",
    "Imacec_minero_rolling3_mean",
    "Imacec_industria_rolling3_mean",
    "Imacec_resto_de_bienes_rolling3_mean",
    "Imacec_comercio_rolling3_mean",
    "Imacec_servicios_rolling3_mean",
    "Imacec_a_costo_de_factores_rolling3_mean",
    "Imacec_no_minero_rolling3_mean",
    "Indice_de_ventas_comercio_real_no_durables_IVCM_rolling3_mean",
    "Precio_leche_rolling3_std",
    "Coquimbo_rolling3_std",
    "Valparaiso_rolling3_std",
    "Metropolitana_de_Santiago_rolling3_std",
    "Libertador_Gral__Bernardo_O_Higgins_rolling3_std",
    "Maule_rolling3_std",
    "Biobio_rolling3_std",
    "La_Araucania_rolling3_std",
    "Los_Rios_rolling3_std",
    "PIB_Agropecuario_silvicola_rolling3_std",
    "PIB_Pesca_rolling3_std",
    "PIB_Mineria_rolling3_std",
    "PIB_Mineria_del_cobre_rolling3_std",
    "PIB_Otras_actividades_mineras_rolling3_std",
    "PIB_Industria_Manufacturera_rolling3_std",
    "PIB_Alimentos_rolling3_std",
    "PIB_Bebidas_y_tabaco_rolling3_std",
    "PIB_Textil_rolling3_std",
    "PIB_Maderas_y_muebles_rolling3_std",
    "PIB_Celulosa_rolling3_std",
    "PIB_Refinacion_de_petroleo_rolling3_std",
    "PIB_Quimica_rolling3_std",
    "PIB_Minerales_no_metalicos_y_metalica_basica_rolling3_std",
    "PIB_Productos_metalicos_rolling3_std",
    "PIB_Electricidad_rolling3_std",
    "PIB_Construccion_rolling3_std",
    "PIB_Comercio_rolling3_std",
    "PIB_Restaurantes_y_hoteles_rolling3_std",
    "PIB_Transporte_rolling3_std",
    "PIB_Comunicaciones_rolling3_std",
    "PIB_Servicios_financieros_rolling3_std",
    "PIB_Servicios_empresariales_rolling3_std",
    "PIB_Servicios_de_vivienda_rolling3_std",
    "PIB_Servicios_personales_rolling3_std",
    "PIB_Administracion_publica_rolling3_std",
    "PIB_a_costo_de_factores_rolling3_std",
    "PIB_rolling3_std",
    "Imacec_empalmado_rolling3_std",
    "Imacec_produccion_de_bienes_rolling3_std",
    "Imacec_minero_rolling3_std",
    "Imacec_industria_rolling3_std",
    "Imacec_resto_de_bienes_rolling3_std",
    "Imacec_comercio_rolling3_std",
    "Imacec_servicios_rolling3_std",
    "Imacec_a_costo_de_factores_rolling3_std",
    "Imacec_no_minero_rolling3_std",
    "Indice_de_ventas_comercio_real_no_durables_IVCM_rolling3_std",
    "Precio_leche",
    "Coquimbo",
    "Valparaiso",
    "Metropolitana_de_Santiago",
    "Libertador_Gral__Bernardo_O_Higgins",
    "Maule",
    "Biobio",
    "La_Araucania",
    "Los_Rios",
    "PIB_Agropecuario_silvicola",
    "PIB_Pesca",
    "PIB_Mineria",
    "PIB_Mineria_del_cobre",
    "PIB_Otras_actividades_mineras",
    "PIB_Industria_Manufacturera",
    "PIB_Alimentos",
    "PIB_Bebidas_y_tabaco",
    "PIB_Textil",
    "PIB_Maderas_y_muebles",
    "PIB_Celulosa",
    "PIB_Refinacion_de_petroleo",
    "PIB_Quimica",
    "PIB_Minerales_no_metalicos_y_metalica_basica",
    "PIB_Productos_metalicos",
    "PIB_Electricidad",
    "PIB_Construccion",
    "PIB_Comercio",
    "PIB_Restaurantes_y_hoteles",
    "PIB_Transporte",
    "PIB_Comunicaciones",
    "PIB_Servicios_financieros",
    "PIB_Servicios_empresariales",
    "PIB_Servicios_de_vivienda",
    "PIB_Servicios_personales",
    "PIB_Administracion_publica",
    "PIB_a_costo_de_factores",
    "PIB",
    "Imacec_empalmado",
    "Imacec_produccion_de_bienes",
    "Imacec_minero",
    "Imacec_industria",
    "Imacec_resto_de_bienes",
    "Imacec_comercio",
    "Imacec_servicios",
    "Imacec_a_costo_de_factores",
    "Imacec_no_minero",
    "Indice_de_ventas_comercio_real_no_durables_IVCM",
]