apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-secret
  namespace: default
  resourceVersion: "164619"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm